### ISSUE TITLE
Problematic changes to CLDR v38 for en_GB

### ISSUE THREAD

**Issue by robrwo** [houseabsolute/DateTime-Locale#29]
Version 38 changes the en_GB abbreviation for "September" from "Sep" to "Sept", so upgrading to DateTime-Locale v1.29 or later can break code that generates/parses short dates.

I have reported it to Unicode CLDR issues https://unicode-org.atlassian.net/browse/CLDR-14412

**Comment by autarch** [comment]
I'm going to close this because there's not anything I want to do to fix it, short of doing a new release whenever CLDR is updated.

It's not clear to me that this change was wrong, though the CLDR maintainers may choose to revert it because of the breakage it can cause.
