### ISSUE TITLE
Install Failure on OSX 

### ISSUE THREAD

**Issue by bpschuck** [houseabsolute/DateTime-Locale#36]
Installing DateTime::Locale on a Macbook Pro M1. OSX Ventura 13.3.1.

Perl v5.30.3.

While installing DateTime::Locale on a new MacBook, test phase fails.

```
t/version-check.t ................ Test2 version 1.302167 required--this is only version 1.302162 at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
BEGIN failed--compilation aborted at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
Compilation failed in require at t/version-check.t line 5.
BEGIN failed--compilation aborted at t/version-check.t line 5.
t/version-check.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
```
Once Test2 is installed DateTime::Locale installs ok.

**Comment by autarch** [comment]
Thanks for the report, but I don't think this is a bug in `DateTime-Locale`. The error is coming from `Test2::Plugin::NoWarnings`. But if I look at that distro, I see that it does indeed require `Test2 >= 1.302167`.

I'm not sure how you tried to install `DateTime-Locale`, but something didn't install all the needed prereqs.

**Comment by bpschuck** [comment]
On 5/16/23 5:30 PM, Dave Rolsky wrote:

> I'm not sure how you tried to install |DateTime-Locale|, but something 
> didn't install all the needed prereqs.

Pretty much brand new Mac out of the box. No other Perl modules yet.

$ perl -MCPAN -e shell

cpan[1]> install DateTime::Locale
.
.
.
.
.

Error occurs while running the version-check.t script.

If it was an issue with Test2::Plugin::NoWarnings, I would expect the 
install of that to fail during its testing before installing.

**Comment by n1vux** [comment]
> No other Perl modules yet.

So this Perl v5.30.3 is the MacOSX Ventura 13.3.1's system bundled Perl in use? You didn't build Perl or install Test2 yourself?

> If it was an issue with Test2::Plugin::NoWarnings, I would expect the
> install of that to fail during its testing before installing.

We would **like** that to be the case (but if you didn't install either `Test2` or the `Test2::Plugin::NoWarnings`, you haven't seen any warnings/errors they threw during install -- you've got an OS bundle, which may have Forced install. 
When it confesses that it's claimed to have installed and be runnable despite unmet prereq version, we should believe the confession. 

(Plugins being late-binding mechanisms are in general notorious for failing at runtime in ways one would expect to fail earlier. This could be  bundling issue or a metadata/makefile-ish issue "over there" in Test2 ? IDK.)

Have you tried installing latest  `Test2::Plugin::NoWarnings` and/or `Test2` explicitly, before installing DateTime things ?

**Comment by bpschuck** [comment]
> So this Perl v5.30.3 is the MacOSX Ventura 13.3.1's system bundled Perl 
> in use? You didn't build Perl or install Test2 yourself?

Correct sir. The Perl that is bundled with the system.

> Have you tried installing latest |Test2::Plugin::NoWarnings| and/or 
> |Test2| explicitly, before installing DateTime things ?

I can try that tomorrow and get back to you. I left my work laptop at work, go figure! ;) 

Sometimes Dist::Zilla doesn't quite figure out all the dependencies correctly. Maybe add Test2 (or Test::Simple which includes/installs Test2) to a `[Prereqs / TestRequires]` stanza in dist.int?

**Comment by autarch** [comment]
>  Sometimes Dist::Zilla doesn't quite figure out all the dependencies correctly. Maybe add Test2 (or Test::Simple which includes/installs Test2) to a [Prereqs / TestRequires] stanza in dist.int?

`DateTime-Locale` already includes a prereq on `Test2::Plugin::NoWarnings`. And the `Test2-Plugin-NoWarnings` distro has the right prereq declared for `Test2`. Adding an additional prereq to `DateTime-Locale` is not necessary if the toolchain is functioning as it should.

You can confirm this yourself by looking at the `META.json` file for each distro.

**Comment by bpschuck** [comment]
Seems it's a bit of an OSX induced issue.

> Have you tried installing latest Test2::Plugin::NoWarnings and/or Test2 explicitly, before installing DateTime things ?

I originally noted installing `Test2` manually before installing `DateTime::Locale` works when I created the issue.

Seems that `Test2::Plugin::NoWarnings` is in the OSX Ventura bundled Perl and the current version.

```
cpan[1]> install Test2::Plugin::NoWarnings                                      
Reading '/Users/Bruce.Schuck/.cpan/Metadata'
  Database was generated on Wed, 17 May 2023 14:54:01 GMT
Test2::Plugin::NoWarnings is up to date (0.09).

grep VERSION /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm
our $VERSION = '0.09';
=head1 VERSION

# This should not happen on a module bundled with the OS
perl -MTest2::Plugin::NoWarnings -e 'print "$Test2::Plugin::NoWarnings::VERSION\n"'
Test2 version 1.302167 required--this is only version 1.302162 at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
BEGIN failed--compilation aborted at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

`DateTime::Locale` is also in pre-installed Perl, but an older version, 1.25.

An install of other modules that want to update `DateTime::Locale` will have issues during the test phase as installing `Finance::Quote` did. Probably similar to whatever issue @DrHyde ran across that caused him to submit Issue #35. 

I'll agree, not a DateDate::Locale issue.

While not a critical problem for those comfortable with Perl, definitely causes headaches for those who are only using Perl because some other program or application depends on it. I ran into it because GnuCash uses `Finance::Quote` (I am the current primary maintainer of F::Q) for retrieving security prices and currency exchange rates. The GnuCash team supplies a wrapper program  around CPAN to install Finance::Quote, and many of its users are not Perl savvy. I guess I may just throw `Test2` into `Finance::Quotes` prerequisites or note that it's needed in the README file. 

Anyway, thanks for your time and helping me uncover the root of the issue.
